{
 "title": "ThongLee-Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service) (flask_http_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service) (flask_http_request_duration_seconds_count{status!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{pod=\"backend-78bb7db6c4-ffksf\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{pod=\"frontend-766f45b885-r65bw\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{pod=\"backend-78bb7db6c4-ffksf\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{pod=\"frontend-766f45b885-r65bw\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_sum{service=\"backend\"}[5m])) * 1000) / sum(rate(flask_http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_sum{service=\"frontend\"}[5m])) * 1000) / sum(rate(flask_http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}